config/routes.rb
Awesomeness::Application.routes.draw do
  root to: 'todos#index'

  resources :todos, only: [:index, :new, :create]

  get '/complete_status', to: 'todos#status'
end

app/models/todo.rb
class Todo < ActiveRecord::Base

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todos_params)
    if @todo.save
      flash[:notice] = 'Todo created successfully.'
      redirect_to root_path
    else
      render :new, notice: 'Invalid todo.'
    end
  end

  def status
    binding.pry
    render json: { success: true }
  end

  private

  def todos_params
    params.require(:todo).permit(:title, :body, :complete)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Awesomeness</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/todos/index.html.haml
%h1 Todo App
%ul
  - @todos.each do |todo|
    %li= todo.title

= link_to 'Make a new todo!', new_todo_path

app/views/todos/new.html.haml
= @todo.errors.full_messages if @todo.errors.present?

= form_for @todo do |f|
  = f.label :title
  = f.text_field :title
  = f.label :body
  = f.text_area :body
  = f.label :complete
  = f.check_box :complete
  = f.submit :submit